#!/usr/bin/env python3
import os
import csv
import time
import struct
import argparse
import numpy as np

import cflib.crtp
from cflib.crazyflie import Crazyflie
from cflib.crazyflie.syncCrazyflie import SyncCrazyflie
from cflib.utils import uri_helper
from cflib.crtp.crtpstack import CRTPPacket


# ============================================================
# Crazyflie trajectory CRTP protocol
# Must match firmware:
#     CRTP_PORT_TRAJECTORY
# ============================================================

TRAJ_PORT = 0x0F


# ============================================================
# Basic Crazyflie params
# ============================================================

def unlock_drone(cf):
    """
    Start outer-loop flight state.
    This matches your original first-drone script.
    """
    cf.param.set_value("app.stateOuterLoop", "1")


def stop_drone(cf):
    """
    Stop / land / switch outer-loop stop state.
    This matches your original first-drone script.
    """
    cf.param.set_value("app.stateOuterLoop", "2")


def apply_mlp(cf):
    cf.param.set_value("app.statemlp", "1")


def apply_kf(cf):
    cf.param.set_value("app.statekf", "1")


def exploration_mode(cf):
    cf.param.set_value("app.stateexp", "1")


def set_initial_params(
    cf,
    MIN_THRESHOLD1=40.0,
    MAX_THRESHOLD1=90.0,
    MIN_THRESHOLD2=40.0,
    MAX_THRESHOLD2=90.0,
    maxSpeed=0.15,
    maxTurnRate=25.0,
    EI=3e-5,
    mu_f=0.4,
):
    """
    Same style as your first-drone script.
    maxSpeed and maxTurnRate are important for trajectory following speed.
    """
    cf.param.set_value("app.MIN_THRESHOLD1", str(MIN_THRESHOLD1))
    cf.param.set_value("app.MAX_THRESHOLD1", str(MAX_THRESHOLD1))
    cf.param.set_value("app.MIN_THRESHOLD2", str(MIN_THRESHOLD2))
    cf.param.set_value("app.MAX_THRESHOLD2", str(MAX_THRESHOLD2))

    cf.param.set_value("app.maxSpeed", str(maxSpeed))
    cf.param.set_value("app.maxTurnRate", str(maxTurnRate))

    cf.param.set_value("kalman.MU_FRICTION", str(mu_f))
    cf.param.set_value("kalman.EI_CONST", str(EI))


def set_servo_params(
    cf,
    target_distance=60.0,
    kp_d=3.0,
    ki_d=2.0,
    kd_d=0.05,
    kp_o=3.0,
    ki_o=1.0,
    kd_o=0.05,
):
    """
    Keep same servo params as your original script, in case firmware needs them.
    """
    cf.param.set_value("app.tgtDist", str(target_distance))
    cf.param.set_value("app.kp_d", str(kp_d))
    cf.param.set_value("app.ki_d", str(ki_d))
    cf.param.set_value("app.kd_d", str(kd_d))
    cf.param.set_value("app.kp_o", str(kp_o))
    cf.param.set_value("app.ki_o", str(ki_o))
    cf.param.set_value("app.kd_o", str(kd_o))


# ============================================================
# CSV loading
# ============================================================

def find_column(fieldnames, candidates):
    """
    Find column by possible names.
    """
    name_map = {name.lower(): name for name in fieldnames}

    for c in candidates:
        if c.lower() in name_map:
            return name_map[c.lower()]

    return None


def load_landing_frame_trajectory_csv(csv_path):
    """
    Load landing-frame trajectory generated by first drone.

    Supported CSV headers:
        x_local,y_local,yaw_local
        x_local_m,y_local_m,yaw_local_rad
        x,y
        x,y,yaw

    Only x/y are sent to Crazyflie firmware.
    yaw is ignored here because your current CRTP trajectory protocol only sends <ff>.
    """
    if not os.path.exists(csv_path):
        raise FileNotFoundError(f"Trajectory CSV not found: {csv_path}")

    points = []

    with open(csv_path, "r", newline="") as f:
        reader = csv.DictReader(f)

        if reader.fieldnames is None:
            raise RuntimeError(f"CSV has no header: {csv_path}")

        fieldnames = reader.fieldnames

        x_col = find_column(
            fieldnames,
            ["x_local", "x_local_m", "x", "x_m"]
        )
        y_col = find_column(
            fieldnames,
            ["y_local", "y_local_m", "y", "y_m"]
        )

        if x_col is None or y_col is None:
            raise RuntimeError(
                f"Cannot find x/y columns in CSV. Found columns: {fieldnames}"
            )

        for row in reader:
            if row[x_col] is None or row[y_col] is None:
                continue

            if row[x_col] == "" or row[y_col] == "":
                continue

            x = float(row[x_col])
            y = float(row[y_col])

            if not np.isfinite(x) or not np.isfinite(y):
                continue

            points.append([x, y])

    traj = np.asarray(points, dtype=np.float32)

    if traj.ndim != 2 or traj.shape[1] != 2 or len(traj) < 2:
        raise RuntimeError(f"Invalid trajectory shape loaded from CSV: {traj.shape}")

    return traj


# ============================================================
# Trajectory preprocessing
# ============================================================

def remove_near_duplicate_points(traj, min_dist=0.01):
    """
    Remove consecutive points that are too close.
    This prevents sending many almost identical waypoints.
    """
    traj = np.asarray(traj, dtype=np.float32)

    if len(traj) <= 2:
        return traj

    kept = [traj[0]]
    last = traj[0]

    for p in traj[1:-1]:
        if np.linalg.norm(p - last) >= min_dist:
            kept.append(p)
            last = p

    if np.linalg.norm(traj[-1] - kept[-1]) > 1e-6:
        kept.append(traj[-1])

    return np.asarray(kept, dtype=np.float32)


def downsample_by_distance(traj, min_dist=0.0):
    """
    Optional distance-based downsampling.

    If min_dist <= 0, keep original trajectory.
    If min_dist = 0.10, keep roughly one point every 10 cm.
    """
    traj = np.asarray(traj, dtype=np.float32)

    if min_dist <= 0.0:
        return traj

    if len(traj) <= 2:
        return traj

    kept = [traj[0]]
    last = traj[0]

    for p in traj[1:-1]:
        if np.linalg.norm(p - last) >= min_dist:
            kept.append(p)
            last = p

    if np.linalg.norm(traj[-1] - kept[-1]) > 1e-6:
        kept.append(traj[-1])

    return np.asarray(kept, dtype=np.float32)


def crop_trajectory_from_nearest_origin(traj):
    """
    Crop trajectory so it starts from the point closest to (0, 0).

    Use this only if your landing-frame full trajectory does not start near origin.
    In the ideal case, the first point should already be close to (0, 0).
    """
    traj = np.asarray(traj, dtype=np.float32)

    d = np.linalg.norm(traj, axis=1)
    idx = int(np.argmin(d))

    cropped = traj[idx:]

    if len(cropped) < 2:
        raise RuntimeError(
            "Cropping from nearest origin leaves fewer than 2 points. "
            "Check whether the trajectory direction is correct."
        )

    print("========== Crop from nearest origin ==========")
    print(f"nearest origin index: {idx}")
    print(f"nearest origin point: {traj[idx]}")
    print(f"original points:      {len(traj)}")
    print(f"cropped points:       {len(cropped)}")

    return cropped.astype(np.float32)


def prepend_origin_if_needed(traj, threshold=0.05):
    """
    If first point is not close to origin, prepend [0, 0].

    This is useful when the second drone starts from landing pose,
    but the planned trajectory begins slightly away from origin.
    """
    traj = np.asarray(traj, dtype=np.float32)

    first_dist = float(np.linalg.norm(traj[0]))

    if first_dist <= threshold:
        return traj

    print("========== Prepending origin ==========")
    print(f"First point is {first_dist:.3f} m away from origin.")
    print("Prepending [0, 0] as first waypoint.")

    traj = np.vstack([
        np.array([[0.0, 0.0]], dtype=np.float32),
        traj
    ])

    return traj.astype(np.float32)


def reverse_trajectory(traj):
    traj = np.asarray(traj, dtype=np.float32)
    return traj[::-1].copy()


def prepare_trajectory(
    traj,
    reverse=False,
    crop_from_origin=False,
    prepend_origin=False,
    prepend_origin_threshold=0.05,
    remove_duplicate_min_dist=0.01,
    downsample_dist=0.0,
):
    """
    Prepare trajectory before sending.
    """
    traj = np.asarray(traj, dtype=np.float32)

    if reverse:
        print("Reversing trajectory.")
        traj = reverse_trajectory(traj)

    if crop_from_origin:
        traj = crop_trajectory_from_nearest_origin(traj)

    if prepend_origin:
        traj = prepend_origin_if_needed(
            traj,
            threshold=prepend_origin_threshold,
        )

    traj = remove_near_duplicate_points(
        traj,
        min_dist=remove_duplicate_min_dist,
    )

    traj = downsample_by_distance(
        traj,
        min_dist=downsample_dist,
    )

    if len(traj) < 2:
        raise RuntimeError("Prepared trajectory has fewer than 2 points.")

    return traj.astype(np.float32)


# ============================================================
# CRTP trajectory sending
# ============================================================

def send_trajectory(cf, traj_points, send_delay=0.01):
    """
    Send XY trajectory to Crazyflie using your current custom CRTP protocol.

    Each point packet:
        struct.pack("<ff", x, y)

    End packet:
        struct.pack("<ff", NaN, NaN)

    This matches your original send_trajectory() function.
    """
    traj_points = np.asarray(traj_points, dtype=np.float32)

    print("========== Sending trajectory ==========")
    print(f"points: {len(traj_points)}")
    print(f"TRAJ_PORT: 0x{TRAJ_PORT:02X}")

    for i, pt in enumerate(traj_points):
        x = float(pt[0])
        y = float(pt[1])

        data = struct.pack("<ff", x, y)

        pk = CRTPPacket()
        pk.port = TRAJ_PORT
        pk.channel = 0
        pk.data = data

        cf.send_packet(pk)

        if i % 20 == 0 or i == len(traj_points) - 1:
            print(f"  sent {i + 1:03d}/{len(traj_points)}: x={x:+.3f}, y={y:+.3f}")

        time.sleep(send_delay)

    # End flag packet: NaN, NaN
    end_data = struct.pack("<ff", float("nan"), float("nan"))

    end_pk = CRTPPacket()
    end_pk.port = TRAJ_PORT
    end_pk.channel = 0
    end_pk.data = end_data

    cf.send_packet(end_pk)

    print("✅ End-of-trajectory flag sent: NaN, NaN")


def print_trajectory_preview(traj, max_rows=10):
    traj = np.asarray(traj, dtype=np.float32)

    print("========== Trajectory preview ==========")
    print(f"Total points: {len(traj)}")
    print(f"First point:  {traj[0]}")
    print(f"Last point:   {traj[-1]}")
    print(f"First dist from origin: {np.linalg.norm(traj[0]):.3f} m")

    print("First points:")
    for i in range(min(max_rows, len(traj))):
        print(f"  {i:03d}: x={traj[i, 0]:+.3f}, y={traj[i, 1]:+.3f}")

    if len(traj) > max_rows:
        print("...")
        print("Last points:")
        start = max(0, len(traj) - max_rows)
        for i in range(start, len(traj)):
            print(f"  {i:03d}: x={traj[i, 0]:+.3f}, y={traj[i, 1]:+.3f}")


# ============================================================
# Main
# ============================================================

def main():
    parser = argparse.ArgumentParser(
        description="Second-drone trajectory sender using landing-frame CSV."
    )

    parser.add_argument(
        "--uri",
        default=None,
        help="Crazyflie URI. If omitted, use URI env or default radio://0/80/2M/E7E7E7E7E7."
    )

    parser.add_argument(
        "--traj_csv",
        type=str,
        required=True,
        help="Path to next_drone_full_trajectory_landing_frame_*.csv"
    )

    parser.add_argument(
        "--maxSpeed",
        type=float,
        default=0.15,
        help="Firmware maxSpeed parameter for trajectory following."
    )

    parser.add_argument(
        "--maxTurnRate",
        type=float,
        default=25.0,
        help="Firmware maxTurnRate parameter."
    )

    parser.add_argument(
        "--send_delay",
        type=float,
        default=0.01,
        help="Delay between trajectory point packets [s]."
    )

    parser.add_argument(
        "--remove_duplicate_min_dist",
        type=float,
        default=0.01,
        help="Remove consecutive points closer than this distance [m]."
    )

    parser.add_argument(
        "--downsample_dist",
        type=float,
        default=0.0,
        help="Optional distance-based downsampling [m]. 0 means no extra downsampling."
    )

    parser.add_argument(
        "--reverse",
        action="store_true",
        help="Reverse trajectory before sending."
    )

    parser.add_argument(
        "--crop_from_origin",
        action="store_true",
        help="Crop trajectory from the point closest to local origin."
    )

    parser.add_argument(
        "--prepend_origin",
        action="store_true",
        help="Prepend [0,0] if first point is not close to origin."
    )

    parser.add_argument(
        "--prepend_origin_threshold",
        type=float,
        default=0.05,
        help="Threshold for deciding whether first point is close to origin [m]."
    )

    parser.add_argument(
        "--dry_run",
        action="store_true",
        help="Only load and preview trajectory. Do not connect to Crazyflie."
    )

    parser.add_argument(
        "--no_unlock",
        action="store_true",
        help="Do not send unlock_drone() after sending trajectory."
    )

    parser.add_argument(
        "--no_arm",
        action="store_true",
        help="Do not send platform arming request."
    )

    args = parser.parse_args()

    if args.uri is None:
        uri = uri_helper.uri_from_env(default="radio://0/80/2M/E7E7E7E7E7")
    else:
        uri = args.uri

    print("========== Second-drone trajectory sender ==========")
    print(f"URI:        {uri}")
    print(f"traj_csv:   {args.traj_csv}")
    print(f"maxSpeed:   {args.maxSpeed}")
    print(f"maxTurnRate:{args.maxTurnRate}")

    traj = load_landing_frame_trajectory_csv(args.traj_csv)

    traj = prepare_trajectory(
        traj,
        reverse=args.reverse,
        crop_from_origin=args.crop_from_origin,
        prepend_origin=args.prepend_origin,
        prepend_origin_threshold=args.prepend_origin_threshold,
        remove_duplicate_min_dist=args.remove_duplicate_min_dist,
        downsample_dist=args.downsample_dist,
    )

    print_trajectory_preview(traj)

    first_dist = float(np.linalg.norm(traj[0]))
    if first_dist > 0.10:
        print("⚠️ Warning:")
        print(f"   First waypoint is {first_dist:.3f} m away from local origin.")
        print("   If the second drone starts at the first-drone landing pose,")
        print("   usually the first waypoint should be close to [0, 0].")
        print("   Consider using --crop_from_origin or --prepend_origin.")

    if args.dry_run:
        print("Dry run enabled. Not connecting to Crazyflie.")
        return

    cflib.crtp.init_drivers()

    cf = Crazyflie(rw_cache="./cache")

    try:
        with SyncCrazyflie(uri, cf=cf) as scf:
            print("✅ Connected.")

            if not args.no_arm:
                print("Arming platform...")
                scf.cf.platform.send_arming_request(True)
                time.sleep(0.5)

            print("Setting initial params...")
            set_initial_params(
                scf.cf,
                maxSpeed=args.maxSpeed,
                maxTurnRate=args.maxTurnRate,
            )

            set_servo_params(scf.cf)

            # If your firmware requires these modes, keep them.
            # If the second-drone firmware is only trajectory tracking,
            # these params can be harmless or you can remove them.
            try:
                apply_mlp(scf.cf)
                apply_kf(scf.cf)
                exploration_mode(scf.cf)
            except Exception as e:
                print(f"⚠️ Mode params failed or unavailable: {e}")

            time.sleep(1.0)

            # Send trajectory first.
            send_trajectory(
                scf.cf,
                traj,
                send_delay=args.send_delay,
            )

            time.sleep(0.5)

            if not args.no_unlock:
                print("Unlocking drone / starting outer loop...")
                unlock_drone(scf.cf)

            print("✅ Trajectory sent to second drone.")
            print("Drone should now follow the received landing-frame trajectory.")
            print("Press Ctrl+C to stop.")

            while True:
                time.sleep(1.0)

    except KeyboardInterrupt:
        print("\n⚠️ KeyboardInterrupt detected.")

    finally:
        print("Stopping drone...")
        try:
            for _ in range(10):
                stop_drone(cf)
                time.sleep(0.1)
        except Exception as e:
            print(f"⚠️ stop_drone failed: {e}")

        try:
            cf.close_link()
        except Exception:
            pass

        print("Disconnected.")


if __name__ == "__main__":
    main()